[programs.localnet]
mysolanaapp = "8ykadQKqpq8bcVfDsPLVWDA4xQZFrcEeGCV2VymFC4fJ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/iyusufali/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
